@tool
extends RefCounted


static func run(manager: EditorUndoRedoManager) -> void:
	manager.clear_history(EditorUndoRedoManager.INVALID_HISTORY, false)
	var graph := ScatterGraph.new()
	var node := ScatterPositionNode.new()
	var service := ScatterUndoService.new(manager, node, Callable())
	service.commit_property(node, &"position", Vector3(1, 0, 0), "Position", "X", UndoRedo.MERGE_ENDS)
	service.commit_property(node, &"position", Vector3(2, 0, 0), "Position", "X", UndoRedo.MERGE_ENDS)
	service.commit_property(node, &"position", Vector3(2, 3, 0), "Position", "Y", UndoRedo.MERGE_ENDS)
	service.commit_property(node, &"space", 2, "Space")
	assert(node.position == Vector3(2, 3, 0))
	assert(node.space == 2)
	var history_id := manager.get_object_history_id(node)
	var history := manager.get_history_undo_redo(history_id)
	assert(history != null)
	assert(history.undo())
	assert(node.space == 1)
	assert(node.position == Vector3(2, 3, 0))
	assert(history.undo())
	assert(node.position == Vector3(2, 0, 0))
	assert(history.undo())
	assert(node.position == Vector3.ZERO)
	assert(history.redo())
	assert(node.position == Vector3(2, 0, 0))

	manager.clear_history(EditorUndoRedoManager.INVALID_HISTORY, false)
	var controller := ScatterGraphController.new()
	controller.configure(graph, null, manager, Callable(), Callable(), Callable(), Callable())
	var created := controller.add_node(&"shape_box", Vector2(10, 20))
	assert(created != null and graph.nodes.size() == 1)
	history_id = manager.get_object_history_id(graph)
	history = manager.get_history_undo_redo(history_id)
	assert(history.undo())
	assert(graph.nodes.is_empty())
	assert(history.redo())
	assert(graph.nodes.size() == 1 and graph.nodes[0] == created)
	controller.delete_nodes([created.node_id])
	assert(graph.nodes.is_empty())
	assert(history.undo())
	assert(graph.nodes.size() == 1 and graph.nodes[0] == created)
	manager.clear_history(EditorUndoRedoManager.INVALID_HISTORY, false)
