name: Scatter Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chickensoft-games/setup-godot@v2
        with:
          version: 4.7.0
          use-dotnet: true
      - run: godot --headless --path . --script res://addons/scatter/tests/run_all.gd
